Fix missing glyphs in chat history
muxable/rtchat pull request #1118
Opened 2023-11-24 08:02 UTC by duncanodhis

I've made some changes to the `lib/screens/settings/chat_history.dart` file. The modifications include using the system font as a fallback to address issues with missing glyphs.

2023-11-24 08:13 UTC, SputNikPlop requested changes

2023-11-24 08:13 UTC, SputNikPlop commented on lib/screens/settings/chat_history.dart
> +import 'dart:ui' as ui;
This is not needed and may be removed.

2023-11-24 08:56 UTC, SputNikPlop commented on android/.settings/org.eclipse.buildship.core.prefs
This file is personal and probably shouldn't be added to the project.

2023-11-24 08:56 UTC, SputNikPlop commented on android/.project
These changes are not needed.

2023-11-24 08:57 UTC, SputNikPlop commented on pubspec.lock
> +  dart: ">=3.2.0-194.0.dev <4.0.0"
Appears you are using either the beta or the main branch, may you switch to the stable branch of flutter

2023-11-27 04:48 UTC, SputNikPlop requested changes

2023-11-27 04:48 UTC, SputNikPlop commented on android/.project
@duncanodhis this doesn't need to be deleted

2023-11-27 08:36 UTC, kevmo314 commented
Looks good for Android. Please remove the eclipse file and it'll be good to merge. Thanks for the contribution!

2023-11-27 11:48 UTC, merged