fix: enable option to test new tts
muxable/rtchat pull request #1244
Opened 2024-05-10 07:50 UTC by SputNikPlop

The new text to speech wasn't quite a hit but this should offer an option for this to be changed via the text to speech settings.

2024-05-10 08:23 UTC, kevmo314 requested changes

2024-05-10 08:23 UTC, kevmo314 commented on lib/screens/settings/tts.dart
> +            SwitchListTile.adaptive(
I don't think we should offer this as an option, nobody will switch to it. We should improve tts based on the feedback and then that would be enough.

2024-05-10 08:23 UTC, kevmo314 commented on lib/screens/settings/tts.dart
> +            SwitchListTile.adaptive(
In particular it seems like most people complained about the speed control not working and tts reading bot messages.

2024-07-26 00:01 UTC, SputNikPlop commented
Closing based on @kevmo314 feedback

2024-07-26 00:01 UTC, closed without merging