feat: completed channel point redemption event config
muxable/rtchat pull request #222
Opened 2021-09-01 05:33 UTC by ryansng

2021-09-01 05:59 UTC, ryansng commented
If you are wondering why are some poll event stuffs being changed in the files it is because I tried to resolve the conflict on web and messed up so I pulled and resolved it locally.

2021-09-01 13:52 UTC, juaoose requested changes
- Missing channel points in `toJson()`, which would prevent storing the settings on shared preferences.
- Also maybe we should think about how we want the pin behaviour to work when redemptions are cancelled or fulfilled (example: maybe if the redemption is cancelled we dont want it to pin)

2021-09-01 13:52 UTC, juaoose commented on lib/models/messages/twitch/eventsub_configuration.dart
> +    channelPointRedemptionEventConfig.isEventPinnable = value;
Missing the object change notification `notifyListeners();`

2021-09-01 14:08 UTC, ryansng commented
> * Also maybe we should think about how we want the pin behaviour to work when redemptions are cancelled or fulfilled (example: maybe if the redemption is cancelled we dont want it to pin)

Currently there's 4 statuses `fulfilled`, `cancelled`, `unfulfilled` and `unknown`. Should I check when it is `cancelled` or `unfulfilled` and unpin it if it is still pinned?

2021-09-02 22:24 UTC, juaoose commented
> > * Also maybe we should think about how we want the pin behaviour to work when redemptions are cancelled or fulfilled (example: maybe if the redemption is cancelled we dont want it to pin)
> 
> Currently there's 4 statuses `fulfilled`, `cancelled`, `unfulfilled` and `unknown`. Should I check when it is `cancelled` or `fulfilled` and unpin it if it is still pinned?

I think something like that would work yes. (tbh I don't have a clear idea on how pins should work for these, because they vary from how each streamer handles reward fulfillment)

The only thing is that sometimes IRL streamers never fulfill some of the rewards so maybe it would be better to unpin unfulfilled rewards after some time?

What do you guys think? @chungwwei @kevmo314

2021-09-02 22:28 UTC, kevmo314 commented
> > > * Also maybe we should think about how we want the pin behaviour to work when redemptions are cancelled or fulfilled (example: maybe if the redemption is cancelled we dont want it to pin)
> > 
> > 
> > Currently there's 4 statuses `fulfilled`, `cancelled`, `unfulfilled` and `unknown`. Should I check when it is `cancelled` or `fulfilled` and unpin it if it is still pinned?
> 
> I think something like that would work yes. (tbh I don't have a clear idea on how pins should work for these, because they vary from how each streamer handles reward fulfillment)
> 
> The only thing is that sometimes IRL streamers never fulfill some of the rewards so maybe it would be better to unpin unfulfilled rewards after some time?
> 
> What do you guys think? @chungwwei @kevmo314

I think we can reasonably assume there's two types of streamers: streamers who want all the rewards to auto-unpin and streamers who want to manually go through fulfillment.

The case of "some rewards require manual fulfillment but not others" seems to get quite complex so I would be ok with making that assumption.

2021-09-06 08:47 UTC, ryansng commented
![image](https://user-images.githubusercontent.com/86465073/132186859-d173ece4-be03-489c-8615-b6899e3b2c7b.png)
The idea here is:
1. If status is `canceled`, event will not pin even if `pin duration > 0`
2. If status is `fulfilled`, event will pin for `pin duration` length
3. If status is `unfulfilled` and
    - `manualClear` is `false`, event will pin for `pin duration` length
    - `manualClear` is `true`, event will pin for 365 days 
4. If status changes from 'unfulfilled' to
   - 'fulfilled', event will pin for 'pin duration' length
   - 'canceled', event will not be pin for any longer (dismissed)

I have no way of confirming if any of these work as I do not know how to test 😅

2021-09-08 00:44 UTC, juaoose commented
> ![image](https://user-images.githubusercontent.com/86465073/132186859-d173ece4-be03-489c-8615-b6899e3b2c7b.png)
> The idea here is:
> 
> 1. If status is `canceled`, event will not pin even if `eventDuration > 0`
> 2. If status is `fulfilled`, event will pin for `eventDuration` length
> 3. If status is `unfulfilled` and
>    
>    * `manualClear` is `false`, event will pin for `eventDuration` length
>    * `manualClear` is `true`, event will pin for 365 days
> 4. If status changes from `unfulfilled` to
>    
>    * `fulfilled`, event will pin for `eventDuration` length
>    * `canceled`, event will not be pin for any longer (dismissed)
> 
> I have no way of confirming if any of these work as I do not know how to test 😅
> 
> Also, say if the broadcaster receives a redemption that requires fulfilment, the status is `unfulfilled` when he initially receives it, how does the broadcaster "fulfil" the redemption? Do I need to code a "swipe-to-fulfil" feature for the event?

Yeah the app doesn't curently allow you to fulfill them (afaik that can not be done via IRC, only through the API) and that might be nice eventually.

2021-09-08 00:48 UTC, juaoose commented on lib/components/chat_history/message.dart
> +// import 'package:firebase_remote_config/firebase_remote_config.dart';
Remote config code can be removed from here since it is no longer used for these events.

2021-09-08 04:55 UTC, ryansng commented
> > ![image](https://user-images.githubusercontent.com/86465073/132186859-d173ece4-be03-489c-8615-b6899e3b2c7b.png)
> > The idea here is:
> > 
> > 1. If status is `canceled`, event will not pin even if `eventDuration > 0`
> > 2. If status is `fulfilled`, event will pin for `eventDuration` length
> > 3. If status is `unfulfilled` and
> >    
> >    * `manualClear` is `false`, event will pin for `eventDuration` length
> >    * `manualClear` is `true`, event will pin for 365 days
> > 4. If status changes from `unfulfilled` to
> >    
> >    * `fulfilled`, event will pin for `eventDuration` length
> >    * `canceled`, event will not be pin for any longer (dismissed)
> > 
> > I have no way of confirming if any of these work as I do not know how to test 😅
> > Also, say if the broadcaster receives a redemption that requires fulfilment, the status is `unfulfilled` when he initially receives it, how does the broadcaster "fulfil" the redemption? Do I need to code a "swipe-to-fulfil" feature for the event?
> 
> Yeah the app doesn't curently allow you to fulfill them (afaik that can not be done via IRC, only through the API) and that might be nice eventually.
> 
> Also, my opinion is that maybe a shorter default for unfulfilled ones could be better, taking into account that we can't fulfill them from the app just yet.


I added a slider for additional pin duration, is this what you are looking for?
![image](https://user-images.githubusercontent.com/86465073/132448615-319ffbbb-1ad2-45bc-82ba-8a3fcf5bfb17.png)

2021-09-08 05:13 UTC, kevmo314 approved these changes

2021-09-08 05:13 UTC, kevmo314 commented on lib/components/chat_panel.dart
> +    if (model.status == 'unfulfilled' && unfulfilledDuration > Duration.zero) {
Can we parse `status` into an enum in the model so we don't have to do string comparisons?

2021-09-08 06:48 UTC, kevmo314 approved these changes

2021-09-08 15:08 UTC, merged