feat: added hypetrain event config
muxable/rtchat pull request #223
Opened 2021-09-02 08:58 UTC by chungwwei

2021-09-02 20:08 UTC, kevmo314 reviewed
Change looks good to me, but I'll let @juaoose officially review :)

2021-09-02 22:19 UTC, juaoose reviewed
Nice, I believe the change to the model needs to be reflected in the widget test.

2021-09-04 04:22 UTC, juaoose requested changes

2021-09-04 04:22 UTC, juaoose commented on lib/models/messages/twitch/hype_train_event.dart
> +        startTimestamp: data['event']['started_at'].toDate(),
These have to be parsed since they're Strings.

2021-09-04 20:44 UTC, juaoose approved these changes

2021-09-05 00:45 UTC, merged