fix: defocus input on tap and drawer open
muxable/rtchat pull request #409
Opened 2022-05-10 06:49 UTC by cswills

closes #5 

changes:
1. add `onDrawerChanged:` and `onEndDrawerChanged:` to home screen `Scaffold` to defocus input on drawer open
2. add `onTap:` to `InkWell` to defocus input when messages are tapped
3. wrap home screen `Scaffold` with `GestureDetector` to defocus input when tapped in most other areas

2022-05-10 17:12 UTC, kevmo314 requested changes

2022-05-10 17:12 UTC, kevmo314 commented on lib/screens/home.dart
> +        onTap: () => FocusManager.instance.primaryFocus?.unfocus(),
Does this break the emote keyboard or command bar?

2022-05-10 18:47 UTC, chungwwei commented
Also happens when you click the people icon. 
maybe adding `FocusManager.instance.primaryFocus?.unfocus();` will fix that too?

https://github.com/muxable/rtchat/blob/main/lib/screens/home.dart#L212

2022-05-10 18:47 UTC, chungwwei commented
Also happens when you click the people icon. 
maybe adding `FocusManager.instance.primaryFocus?.unfocus();` will fix that too?

https://github.com/muxable/rtchat/blob/main/lib/screens/home.dart#L212

2022-05-10 19:05 UTC, cswills commented
> Also happens when you click the people icon. maybe adding `FocusManager.instance.primaryFocus?.unfocus();` will fix that too?
> 
> https://github.com/muxable/rtchat/blob/main/lib/screens/home.dart#L212

https://github.com/cswills/rtchat/blob/ae822cfae8e80b4bafda7c0285311e73b7b5d5eb/lib/screens/home.dart#L174-L175
This code defocuses input when the people icon is pressed.

2022-05-25 05:43 UTC, kevmo314 commented on lib/screens/home.dart
> +        onTap: () => FocusManager.instance.primaryFocus?.unfocus(),
Oh I see, sounds good 👍

2022-05-25 05:44 UTC, kevmo314 approved these changes

2022-05-26 23:44 UTC, merged